#!/usr/bin/env php
<?php

declare(strict_types=1);

if (php_sapi_name() != 'cli') {
    die("<h1>Only in CLI mode!</h1>");
}

if (posix_getuid() != 0) {
    die("Pleas run phost with sudo!\n");
}

require_once __DIR__ . '/bootstrap.php';

use PHost\Commands\BannerCommand;

BannerCommand::init();

$domain = readline('>>> domain: ');
$extension = readline('>>> extension: ');

$app->create($domain, $extension);
